#!/usr/bin/env bash
# Build a fake MESA git repository at $1 and print its HEAD sha.
#
# Just enough of MESA for mesa_test to drive: ./clean, ./install (writes
# build.log and a testhub.yml in MESA's real format), and per-module
# test_suite/{list_tests,each_test_run}. each_test_run writes each test's
# testhub.yml the way MESA's does -- run_optional / fpe_checks /
# resolution_factor read from the same environment variables -- and logs
# the environment every build and test ran with to $MESA_DIR/../env_log.txt
# so the harness can check what mesa_test actually set.
set -euo pipefail
dest=$1
mkdir -p "$dest"
cd "$dest"
git init -q -b main .

cat > clean <<'EOF'
#!/usr/bin/env bash
rm -f build.log testhub.yml
EOF

cat > install <<'EOF'
#!/usr/bin/env bash
echo "install fpe=${MESA_FPE_CHECKS_ON:-unset}" >> "$MESA_DIR/../env_log.txt"
cat > testhub.yml <<'YML'
# This file is generated by math/test (see src/test_math.f90)
---
compiler: 'gfortran'
compiler_version: '15.2.0'
sdk_version: 'aarch64-macos-26.3.2'
math_backend: 'CRMATH'
YML
echo "MESA installation was successful" > build.log
EOF

# (a function rather than an associative array: macOS ships bash 3.2)
tests_for() {
  case $1 in
    star) echo "fake_alpha fake_beta" ;;
    binary) echo "fake_gamma" ;;
    *) echo "" ;;
  esac
}
for mod in star binary astero; do
  mkdir -p "$mod/test_suite"
  {
    echo '#!/usr/bin/env bash'
    n=1
    for t in $(tests_for $mod); do echo "echo \"$n $t\""; n=$((n+1)); done
  } > "$mod/test_suite/list_tests"
  for t in $(tests_for $mod); do mkdir -p "$mod/test_suite/$t"; touch "$mod/test_suite/$t/.keep"; done
  cat > "$mod/test_suite/each_test_run" <<EOF
#!/usr/bin/env bash
# no argument: run every test in this module, like MESA's each_test_run
if [ -z "\$1" ]; then
  for n in \$(./list_tests | awk '{print \$1}'); do "\$0" "\$n"; done
  exit 0
fi
name=\$(./list_tests | awk -v n="\$1" '\$1==n {print \$2}')
echo "test $mod/\$name skip_optional=\${MESA_SKIP_OPTIONAL-unset} fpe=\${MESA_FPE_CHECKS_ON:-unset} res=\${MESA_TEST_SUITE_RESOLUTION_FACTOR:-unset}" >> "\$MESA_DIR/../env_log.txt"
cd "\$name"
{
  echo "---"
  echo "test_case: \$name"
  echo "module: :$mod"
  echo "omp_num_threads: \${OMP_NUM_THREADS:-0}"
  if [ -z "\$MESA_SKIP_OPTIONAL" ]; then echo "run_optional: true"; else echo "run_optional: false"; fi
  if [ -z "\$MESA_FPE_CHECKS_ON" ]; then echo "fpe_checks: false"; else echo "fpe_checks: true"; fi
  echo "resolution_factor: \${MESA_TEST_SUITE_RESOLUTION_FACTOR:-1}"
  echo "inlists:"
  echo "  - inlist: inlist_fake"
  echo "    runtime_minutes: 0.1"
  echo "    steps: 10"
  echo "checksum: 0123456789abcdef0123456789abcdef"
  echo "outcome: :pass"
} > testhub.yml
EOF
done

chmod +x clean install */test_suite/list_tests */test_suite/each_test_run
git add -A
git -c user.email=fake-mesa@example.test -c user.name='Fake MESA' commit -qm 'fake MESA'
git rev-parse HEAD
